# __Assignment 9__ : NumPy

## __Task 1__

In [5]:
import numpy as np

arr1d = np.array([1,2,3,4,5,6,7,8,9,10])

arr2d = np.array([[1,2,3],[4,5,6]])

arr = [10,20,30,40,50]

numpy_arr = np.array(arr)

In [8]:
# Shape of arrays
print(arr1d.shape)
print(arr2d.shape)
print(numpy_arr.shape)

(10,)
(2, 3)
(5,)


In [ ]:
# Data type of Arrays
print(arr1d.dtype)
print(arr2d.dtype)
print(numpy_arr.dtype)

int64
int64
int64


## __Task 2__

In [ ]:
# Performing Arithmetics

A = np.array([10,20,30,40])
B = np.array([1,2,3,4])

addition = np.add(A, B)
subtract = np.subtract(A, B)
multipy = np.multiply(A, B)
division = np.divide(A, B)
power = np.power(A, 2)

In [10]:
# Printing Results

print(addition)
print(subtract)
print(multipy)
print(division)
print(power)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[ 100  400  900 1600]


## __Task 3__

In [12]:
# Performing Functions

values = np.array([2,4,6,8,10])

sqrt = np.sqrt(values)
exp = np.exp(values)
log = np.log(values)
summation = np.sum(values)
cumsum = np.cumsum(values)

In [13]:
# Printing results

print(sqrt)
print(exp)
print(log)
print(summation)
print(cumsum)

[1.41421356 2.         2.44948974 2.82842712 3.16227766]
[7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
[0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]
30
[ 2  6 12 20 30]


## __Task 4__

In [ ]:
data = np.array([[10,20,30],[40,50,60],[70,80,90]])

sum_rows = np.sum(data, axis=1)
sum_columns = np.sum(data, axis=0)
minimum = np.min(data)
maximum = np.max(data)
mean = np.mean(data)

In [16]:
print(sum_rows)
print(sum_columns)
print(minimum)
print(maximum)
print(mean)

[ 60 150 240]
[120 150 180]
10
90
50.0


## __Task 5__

In [17]:
marks = np.array([78,85,90,66,72,88,95,60])

mean2 = np.mean(marks)
median = np.median(marks)
variance = np.var(marks)
std_dev = np.std(marks)
min_val = np.min(marks)
max_val = np.max(marks)
range = np.max(marks) - np.min(marks)

In [20]:
print(mean2)
print(median)
print(variance)
print(std_dev)
print(min_val, max_val)
print(range)

79.25
81.5
134.1875
11.583932838203095
60 95
35


## __Task 6__

In [ ]:
sorted = np.sort(marks)
p25 = np.percentile(marks, 25)
p50 = np.percentile(marks, 50)
p75 = np.percentile(marks, 75)
more_than_avg = np.sum(marks > np.mean(marks))


70.5 81.5 88.5


In [23]:
print(sorted)
print(p25, p50, p75)
print(more_than_avg)

[60 66 72 78 85 88 90 95]
70.5 81.5 88.5
4


## __Task 7__ : Sales Analysis

In [ ]:
sales = np.array([1200, 1500, 900, 2000, 1800, 1700, 1600])

total_sales = np.sum(sales)
avg_daily = np.mean(sales)
lowest = np.min(sales)
highest = np.max(sales)
std_d = np.std(sales)
avg_sales = np.sum(sales > np.mean(sales))

In [25]:
print(total_sales)
print(avg_daily)
print(lowest)
print(highest)
print(std_d)
print(avg_sales)

10700
1528.5714285714287
900
2000
345.2298849598449
4
